framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'

        channel_policy:
            urgent: ['chat/slack']
            high: ['chat/slack']
            medium: ['browser']
            low: ['browser']

        admin_recipients:
            - { email: '%env(ADMIN_EMAIL)%' }
